#!/bin/bash
CPUUSAGE=$(mpstat -P ALL| awk '$12 ~ /[0-9]+/ { print 100 - $12"%"}')
CPUTEMP=$(sensors | awk '$1 ~ /Core/ { print $3 }')
echo CPU Cores {$CPUUSAGE} {$CPUTEMP}
echo CPU Cores {$CPUUSAGE} {$CPUTEMP}
echo "#FFFFFF"
case $BLOCK_BUTTON in
        3) rofi -combi-modi window,drun,ssh -width 17 -show combi -e "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac
exit 0
