#!/bin/bash
TEMPERATURE=$(nvidia-smi --format=csv,noheader,nounits --query-gpu=temperature.gpu)
echo GPU $TEMPERATURE\cº
echo "No GPU"
echo "#FFFFFF"
case $BLOCK_BUTTON in
  3) nvidia-settings;;  # open xserver nvidia settings on right click.
esac
exit 0

